import type { Metadata } from "next";
import { AR_One_Sans } from "next/font/google";
import "./globals.css";

const inter = AR_One_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Cameelers",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        // use theme from daisy ui
        <html lang="es" data-theme="mytheme">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
